### ISSUE TITLE
MultiQC 1.21 doesn't support genomic_dna section

### ISSUE THREAD

**Issue by AlanLonguet** [nf-core/spatialvi#84]
### Description of the bug

When launching this workflow : 

```sh
nextflow run nf-core/spatialvi -r dev \
   -profile docker \
   --input /shared/samplesheet_spaceranger.csv \
   --spaceranger_probeset /shared/Visium_Human_Transcriptome_Probe_Set_v1.0_GRCh38-2020-A.csv \
   --spaceranger_reference /shared/homo_sapiens_chr22_reference.tar.gz \
   --qc_min_counts 5 \
   --qc_min_genes 3 \
   --outdir /shared/test_output
```

I had this error at the MultiQC step : 

```sh
    /// MultiQC 🔍 | v1.21

  |           multiqc | MultiQC Version v1.23 now available!
  |           multiqc | Search path : /home/alanl/work/c8/6af00af8c6888f021e0e867cbe27d2
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 61/61
  |    custom_content | nf-core-spatialvi-summary: Found 1 sample (html)
  |    custom_content | nf-core-spatialvi-methods-description: Found 1 sample (html)
  |            fastqc | Found 2 reports
  ╭────────────── Oops! The 'spaceranger' MultiQC module broke... ───────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/MultiQC/MultiQC/issues                                    │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ 52/web_summary.html                                                          │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 75 │
  │     output = mod()                                                           │
  │              ^^^^^                                                           │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/spaceranger/ │
  │     n["count"] = self.parse_count_html()                                     │
  │                  ^^^^^^^^^^^^^^^^^^^^^^^                                     │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/spaceranger/ │
  │     description=self.spacerangercount_plots_conf["genomic_dna"]["description │
  │                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^              │
  │ KeyError: 'genomic_dna'                                                      │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  |           multiqc | Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  |           multiqc | Plots       : multiqc_plots
  |           multiqc | MultiQC complete
```

Looking up issues on Github I found this was related to this issue (https://github.com/MultiQC/MultiQC/issues/2428) that was fixed in 1.22 (https://github.com/MultiQC/MultiQC/releases/tag/v1.22)

I then forked spatialvi and updated the multiqc version on my fork and it worked : https://github.com/Alan-pad/spatialvi/commit/10776c3243479357d1432d8d9953b5257a3a5653

### Command used and terminal output

```console
nextflow run nf-core/spatialvi -r dev \
   -profile docker \
   --input /shared/samplesheet_spaceranger.csv \
   --spaceranger_probeset /shared/Visium_Human_Transcriptome_Probe_Set_v1.0_GRCh38-2020-A.csv \
   --spaceranger_reference /shared/homo_sapiens_chr22_reference.tar.gz \
   --qc_min_counts 5 \
   --qc_min_genes 3 \
   --outdir /shared/test_output

    /// MultiQC 🔍 | v1.21

  |           multiqc | MultiQC Version v1.23 now available!
  |           multiqc | Search path : /home/alanl/work/c8/6af00af8c6888f021e0e867cbe27d2
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 61/61
  |    custom_content | nf-core-spatialvi-summary: Found 1 sample (html)
  |    custom_content | nf-core-spatialvi-methods-description: Found 1 sample (html)
  |            fastqc | Found 2 reports
  ╭────────────── Oops! The 'spaceranger' MultiQC module broke... ───────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/MultiQC/MultiQC/issues                                    │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ 52/web_summary.html                                                          │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 75 │
  │     output = mod()                                                           │
  │              ^^^^^                                                           │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/spaceranger/ │
  │     n["count"] = self.parse_count_html()                                     │
  │                  ^^^^^^^^^^^^^^^^^^^^^^^                                     │
  │   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/spaceranger/ │
  │     description=self.spacerangercount_plots_conf["genomic_dna"]["description │
  │                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^              │
  │ KeyError: 'genomic_dna'                                                      │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  |           multiqc | Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  |           multiqc | Plots       : multiqc_plots
  |           multiqc | MultiQC complete
```

**Comment by fasterius** [comment]
Thanks for the reminder! The MultiQC module wasn't updated the last time I was working on this, but now it is. This should now work on the `dev` branch.
